name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18.0-beta1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: go test -cover ./...
